# Generated by Django 4.1.6 on 2023-02-02 16:27

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GMImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=pathlib.PureWindowsPath('C:/Users/Sam/OneDrive/Documents/DTD/TreesFromForrest/TreeVsForrest/base/media/images'))),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
