# Generated by Django 4.1.6 on 2023-02-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleMaps', '0002_alter_gmimage_latitude_alter_gmimage_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmimage',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gmimage',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
