# Generated by Django 4.1.6 on 2023-02-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleMaps', '0004_gmimage_url_alter_gmimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmimage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
